# Generated by Django 4.2.7 on 2024-06-19 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prescription_ongo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescribe_time', models.TimeField()),
                ('total_tablets', models.PositiveSmallIntegerField()),
                ('no_of_times_per_day', models.PositiveSmallIntegerField()),
                ('no_of_tablets_per_use', models.PositiveSmallIntegerField()),
                ('general_description', models.TextField()),
                ('prescribed_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
