# Generated by Django 4.2.7 on 2026-06-10 15:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('prescription_ongo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('invited_email', models.EmailField(max_length=254)),
                ('medical_institution', models.CharField(max_length=500)),
                ('portal_type', models.CharField(max_length=20)),
                ('used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='clinicuser',
            name='portal_type',
            field=models.CharField(blank=True, choices=[('hospital', 'Hospital'), ('pharmacy', 'Pharmacy')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='clinicuser',
            name='role',
            field=models.CharField(choices=[('head', 'Head'), ('staff', 'Staff')], default='staff', max_length=10),
        ),
    ]
