# Generated by Django 4.2.7 on 2024-06-19 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prescription_ongo', '0002_prescribe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescribe',
            name='prescribed_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
