# Generated by Django 4.2.7 on 2026-06-10 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription_ongo', '0002_staffinvite_clinicuser_portal_type_clinicuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffinvite',
            name='role',
            field=models.CharField(choices=[('head', 'Head'), ('staff', 'Staff')], default='staff', max_length=10),
        ),
    ]
