# Generated by Django 4.2.7 on 2024-06-19 14:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription_ongo', '0003_alter_prescribe_prescribed_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescribe',
            name='first_time',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
