# Generated by Django 4.2.7 on 2024-06-20 15:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription_ongo', '0004_prescribe_first_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescribe',
            name='drug_name',
            field=models.CharField(default='no default name', max_length=800),
        ),
        migrations.AddField(
            model_name='prescribe',
            name='initial_proposed_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 20, 17, 2, 38, 898943)),
        ),
        migrations.AddField(
            model_name='prescribe',
            name='recent_proposed_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 20, 17, 2, 38, 898943)),
        ),
        migrations.AddField(
            model_name='prescribe',
            name='reverse_value',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='prescribe',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 20, 17, 2, 38, 898943)),
        ),
        migrations.AddField(
            model_name='prescribe',
            name='total_tablets_dynamic',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
