# Generated by Django 4.2.7 on 2024-06-20 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription_ongo', '0005_prescribe_drug_name_prescribe_initial_proposed_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescribe',
            name='initial_proposed_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='prescribe',
            name='recent_proposed_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='prescribe',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
