# Generated by Django 4.2.7 on 2024-06-20 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription_ongo', '0006_alter_prescribe_initial_proposed_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescribe',
            name='drug_name',
            field=models.CharField(max_length=800),
        ),
    ]
