# Generated by Django 4.2.7 on 2024-06-22 12:08

from django.db import migrations, models
import prescription_ongo.models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription_ongo', '0008_clinicuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='phone_number',
            field=models.CharField(max_length=20, null=True, validators=[prescription_ongo.models.validate_and_normalize_phone_number]),
        ),
    ]
