# Generated by Django 4.2.7 on 2024-06-30 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription_ongo', '0009_alter_patient_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicuser',
            name='designation',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
